# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d0bb1a01bb62b540510f0af891d96cfe438500957fb417dedea3d3983d03d2a1cc309b95863bc509f2ff6d50b9f348a796492311e5a2b6fe2add981e1fcf6d7

test:
  secret_key_base: c726f3b6881e20521ed95ce30920f1894ac1db77323a5a84f7c2ac269822d647e216a1799c16134fc68b70426fc86fbdfae0015b7d8e193f484c222f76c07981

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  S3_BUCKET_NAME: marbletrader
  AWS_ACCESS_KEY_ID: AKIAIKVN6JU76DNXPMDQ
  AWS_SECRET_ACCESS_KEY: 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